// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateTaskController from "./create_task_controller"
application.register("create-task", CreateTaskController)

import EditTaskController from "./edit_task_controller"
application.register("edit-task", EditTaskController)

import GameController from "./game_controller"
application.register("game", GameController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import UpdateTimerController from "./update_timer_controller"
application.register("update-timer", UpdateTimerController)
