meta_product_name: "Virtual Work Buddy"
meta_title: "Virtual Work Buddy - Make homeoffice a happier place"
meta_description: "A productivity app as a game"
meta_image: "ogimage.png" # should exist in `app/assets/images/`
